//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zadatak
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBElementC
    {
        public int Id { get; set; }
        public string Grupa { get; set; }
        public Nullable<int> Vrednost { get; set; }
        public string IdElementP { get; set; }
    
        public virtual DBElementP DBElementP { get; set; }
    }
}
