//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zadatak
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBElementP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DBElementP()
        {
            this.DBElementCs = new HashSet<DBElementC>();
        }
    
        public int RedniBroj { get; set; }
        public string IdentifikacioniKod { get; set; }
        public Nullable<System.DateTime> DateAndTimeAdded { get; set; }
        public int p { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DBElementC> DBElementCs { get; set; }
    }
}
